name: Package and Release

on:
  push:
    tags:
      - "trade-v*"
      - "guild-v*"
      - "!**-alpha**"
      - "!**-beta**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning

  release-trade:
    runs-on: ubuntu-latest
    if: always() && needs.lint.result != 'cancelled' && startsWith(github.ref_name, 'trade-')
    needs: lint
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -m .pkgmeta-trade -n "{package-name}-{project-version}{classic}"

  release-guild:
    runs-on: ubuntu-latest
    if: always() && needs.lint.result != 'cancelled' && startsWith(github.ref_name, 'guild-')
    needs: lint
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -m .pkgmeta-guild -n "{package-name}-{project-version}{classic}"
